import { createEmptyExam, type Exam, type ExamBlock } from "@/domain/exam";

export const rendererBlocks: ExamBlock[] = [
  {
    id: "instruction",
    type: "instruction",
    startsNewQuestion: false,
    order: 0,
    content: "اقرأ الوثائق بعناية",
  },
  {
    id: "document",
    type: "text-document",
    startsNewQuestion: false,
    order: 1,
    instruction: "اقرأ النص",
    title: "وثيقة تاريخية",
    content: "حصل المغرب على الاستقلال سنة 1956.",
    source: "الأرشيف",
    reference: "ص 12",
    bordered: true,
    points: 1,
  },
  {
    id: "image",
    type: "image",
    startsNewQuestion: false,
    order: 2,
    imageId: "image-asset",
    title: "خريطة المغرب",
    caption: "وثيقة 1",
    source: "الأطلس",
    width: 75,
    alignment: "center",
    bordered: true,
    points: 1,
  },
  {
    id: "question",
    type: "question",
    startsNewQuestion: true,
    order: 3,
    question: "اشرح أسباب الحدث",
    answerMode: "lines",
    answerLines: 3,
    points: 2,
  },
  {
    id: "definition",
    type: "definition",
    startsNewQuestion: true,
    order: 4,
    instruction: "عرف ما يلي",
    items: [{ id: "term", term: "الاستقلال", answerLines: 2, points: 1 }],
  },
  {
    id: "true-false",
    type: "true-false",
    startsNewQuestion: true,
    order: 5,
    instruction: "ضع علامة",
    statements: [
      { id: "statement", text: "استقل المغرب سنة 1956", points: 0.5 },
    ],
  },
  {
    id: "mcq",
    type: "multiple-choice",
    startsNewQuestion: true,
    order: 6,
    question: "اختر الجواب",
    options: [
      { id: "option-a", text: "1956" },
      { id: "option-b", text: "1975" },
    ],
    allowMultipleAnswers: false,
    points: 1,
  },
  {
    id: "fill",
    type: "fill-blank",
    startsNewQuestion: true,
    order: 7,
    instruction: "أكمل",
    segments: [
      { type: "text", value: "استقل المغرب سنة " },
      { type: "blank", id: "blank", width: 8 },
      { type: "text", value: "." },
    ],
    points: 1,
  },
  {
    id: "table",
    type: "table",
    startsNewQuestion: true,
    order: 8,
    columns: [
      { id: "year", label: "السنة" },
      { id: "event", label: "الحدث" },
    ],
    rows: [
      {
        id: "row",
        cells: [
          { columnId: "year", value: "1956" },
          { columnId: "event", value: "الاستقلال" },
        ],
      },
    ],
    showHeader: true,
    points: 2,
  },
  {
    id: "matching",
    type: "matching",
    startsNewQuestion: true,
    order: 9,
    instruction: "صل بسهم",
    leftItems: [{ id: "left", text: "المسيرة الخضراء" }],
    rightItems: [{ id: "right", text: "1975" }],
    shuffleRight: true,
    points: 1,
  },
  {
    id: "essay",
    type: "essay",
    startsNewQuestion: true,
    order: 10,
    context: "شهد المغرب تحولات مهمة.",
    instruction: "اكتب موضوعا مقاليا",
    topics: [{ id: "topic", text: "مقدمة وعرض وخاتمة" }],
    points: 7,
  },
  {
    id: "free",
    type: "free-text",
    startsNewQuestion: false,
    order: 11,
    content: "ملاحظة مهمة",
    variant: "note",
  },
  {
    id: "separator",
    type: "separator",
    startsNewQuestion: false,
    order: 12,
    style: "line",
  },
  { id: "break", type: "page-break", startsNewQuestion: false, order: 13 },
  {
    id: "timeline",
    type: "timeline",
    startsNewQuestion: true,
    order: 14,
    title: "محطات تاريخية",
    orientation: "horizontal",
    showDates: true,
    events: [
      { id: "event-1912", date: "1912", label: "الحماية" },
      { id: "event-1956", date: "1956", label: "الاستقلال" },
    ],
    points: 2,
  },
  {
    id: "chart",
    type: "chart",
    startsNewQuestion: true,
    order: 15,
    title: "السكان",
    chartType: "bar",
    labels: [
      { id: "category-1960", label: "1960" },
      { id: "category-1970", label: "1970" },
    ],
    series: [{ id: "population", name: "السكان", values: [12, 15] }],
    showLegend: true,
    showValues: true,
    yAxisLabel: "مليون",
    points: 2,
  },
];

export function createRendererTestExam(language: "ar" | "fr" = "ar"): Exam {
  const exam = createEmptyExam({
    id: "renderer-exam",
    now: "2026-08-22T12:00:00.000Z",
    documentLanguage: language,
    templateId: "moroccan-college-classic",
  });
  return {
    ...exam,
    metadata: {
      title: language === "ar" ? "فرض محروس رقم 1" : "Contrôle continu n° 1",
      academicYear: "2026-2027",
      institution: "Collège Al Atlas",
      regionalAcademy: "Rabat-Salé-Kénitra",
      provincialDirectorate: "Rabat",
      level: language === "ar" ? "الثالثة إعدادي" : "3e année collège",
      subject: language === "ar" ? "الاجتماعيات" : "Histoire-Géographie",
      teacherName: "Mme Amrani",
      durationMinutes: 60,
      totalPoints: 20,
      examNumber: "1",
    },
    sections: [
      {
        id: "history",
        title: language === "ar" ? "مادة التاريخ" : "Histoire",
        points: 20,
        blocks: rendererBlocks,
      },
    ],
  };
}
